### ISSUE TITLE
Add a tag for first stable version

### ISSUE THREAD

**Issue by tdutrion** [czechphp/ico-validator#1]
Hi!

I am planning  to  use this validator in a professional project and I was wondering whether you'd be able to tag a first release (1.0.0), so that we can have a proper dependency in that project.

Thanks in advance
Thomas

**Comment by Tetragramat** [comment]
Released version https://github.com/czechphp/ico-validator/releases/tag/v1.0.0

**Comment by tdutrion** [comment]
Thanks very much!
